language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - android-sdk-preview-license-.+
env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.3
  - ADB_INSTALL_TIMEOUT=5
before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
  - echo yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew clean build

